### ISSUE TITLE
Firing Animation Bug

### ISSUE THREAD

**Issue by RPGShoulderDevil** [Moffein/SniperClassic#3]
After using "Spotter drone", Sniper's firing animation then bugs out and he snaps back into idle stance, then back out, very quickly about halfway through the animation for the rest of the run. Can sometimes be resolved by recalling the drone in certain ways but otherwise bugs out the animation

Thanks for the mod, it's amazing so far and really impresses me with the quality put into it!

**Comment by Moffein** [comment]
Was a long time coming, but the anims have been fixed in the current in-development version of the mod.
