### ISSUE TITLE
Strange audio issue while scoped?

### ISSUE THREAD

**Issue by Ties-afk** [Moffein/SniperClassic#30]
Hi,

I was wondering if this is a known issue or an issue on our end:

The firing sound effect for the default M1 sniper is very muffled most of the time while shooting in the scoped mode, and sometimes it even cuts-off mid effect. It rarily sounds correctly like it does from third person. Like it's being pushed out of the audio mix or something

Sometimes it does sound correctly like it does in the third person, but I have no idea what is causing it. It doesn't seem to have anything to do with orientation or height of the camera, it just seems to happen most of the time and then works correctly for a few shots.

It doesn't seem to be a mod conflict, because it happens to me when just installing the Sniper standalone.  We're on V1.5.5 (latest as of writing)

I also noticed another (very) tiny issue: in Third Person scope mode, you can see your own aim laser but the origin point is above the sniper, which looks a bit weird.

Love the Sniper mod btw and how it's manages to feel distinct from Railgunner!

**Comment by Moffein** [comment]
I've never had the audio issue while scoped, so it might be a thing on your end. Does it happen for everyone you play with?
Send r2modman mod profile code if you can, and I'll look into it.

Laser thing is a known bug, I think I was originally planning address it some years ago but forgot about it.

**Comment by Ties-afk** [comment]
Hi, I made a seperate mod profile that just has the DebugToolkit + Sniper to test what's happening, and I think I was wrong initially and it dóes actually have everything to with where the camera is pointing

I've made a recording here: https://streamable.com/dljftw 
(I have no idea why it recorded my cursor, also skill issue at 0:15)


It seems that whenever you're aiming above a certain height in the y-axis, the sound suddenly starts to dampen. I didn't show it in the recording but it happens on all zoom levels / zoom levels don't seem to matter.

I thought that maybe it's some weird issue where the game is occluding the noise because it thinks you're underground if you're aiming up (I doubt there's even a system like that in the game at all), but the issue also happens if you're high up in the air


I don't think it matters but I'll send you our modpack code just in case, it's a slightly altered version of the RiskyStarter pack 018d3273-6f0c-9178-4afb-433f3fc9cdbd

**Comment by Moffein** [comment]
Got around to testing with your modpack, but I couldn't seem to reproduce the bug on my end even when trying it out on different maps and with different scope zoom levels.

It might be worth a shot to try deleting and reinstalling SniperClassic in case something weird happened with the soundbank, though I'm doubtful that's the cause. Alternatively, it could be caused be some system audio setting or some in-game setting, but I don't have any leads on that.

**Comment by Ties-afk** [comment]
Hi Moffein,

Thank you for taking the time to test, I'm glad it seems to be an issue on our end. 

I'll try some more things with the group I play with, maybe a try a complete clean reinstall of r2modman.
I thought it couldn't be a mod conflict, since I did try creating a seperate mod profile with just the sniper mod (and all of its dependancies ofc) but I have no idea if r2modman profiles are completely seperate

I'll update if I find a specific cause / mod conflict

**Comment by Moffein** [comment]
A complete reinstall of r2modman is probably unnecessary since each profile is completely separate and has its own copy of mods. Is the bug happening for everyone you play with?

**Comment by Ties-afk** [comment]
I've been able to fix the issue on my end. I've done a complete reinstall of RoR2 and r2modman, changed install location for both for the reinstall and also lowered the audio format for my sound output in windows and...somehow it's fixed. Not sure whatever was causing it but I'll take it

My friend streamed today for me, and he seemingly has a different issue where his gun sfx just sound garbled every other shot, the Y-axis thing I had does not happen for him at all. I'll advise him to at least do a reinstall of the mod as well.

Thanks for the help, sent you a tip on ko-fi for the assist (and the great mods you've put out)!
