### ISSUE TITLE
Sniper is unaffected by soldier syringe?

### ISSUE THREAD

**Issue by f1ow03** [Moffein/SniperClassic#8]
Can someone clarify how exactly it works with Sniper? Does it increase reload window or smth? Is there any article/readme file to check how different items affect Sniper?
Also, thanks for this awesome mod! Character is very balanced and its playstyle is absolutely fantastic!

**Comment by Moffein** [comment]
Currently, Syringes only increase the charge speed of Steady Aim. In the next update, the cooldown of SPOTTER: Feedback will be affected by attack speed as well.
Once the DLC releases, I plan to have Sniper's good/perfect reload window increase in size with attack speed, as well as adding the weak point mechanic in some form.
Glad to hear you're enjoying the mod!
